scan_timeout = 10
add_newline = false
[directory]
truncation_length = 8
truncation_symbol = "…/"
[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false
[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false
show_always = true
[time]
disabled = false
utc_time_offset = "+2"
